### ISSUE TITLE
Production uses webpack watcher

### ISSUE THREAD

**Issue by brettimus** [inkandswitch/livebook#10]
(Brain dumping prior to release)

We have to list all devDeps as deps in the package.json because our app frontend is built on heroku with `webpack --watch`. Could switch to `webpack -p` for production build to decrease filesizes and provide separation of deps / devdeps

**Comment by luciasantamaria** [comment]
@brettimus Is this still an issue or can it be closed?

**Comment by brettimus** [comment]
@luciasantamaria Still an issue but not causing issues. Will close!
