### ISSUE TITLE
Links on notebook don't work

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#14]
Hover on link (for instance: "adapted from this notebook by Justin Bozonier"). Blurb opens with link URL, click on it, another blurb opens to modify link. Linked page does not open.

**Comment by brettimus** [comment]
Going to be trickier than I thought but hopefully not actually that tricky

https://github.com/yabwe/medium-editor/issues/918

**Comment by adamwiggins** [comment]
To keep it simple, the design I suggest here is:

* Clicking the blue link (e.g. "this notebook") in the text opens the link as usual, e.g. it is an href. This is what needs to be implemented.
* Hovering creates the small white-on-black dialog showing the link. The user can move the mouse down and click it to open the edit dialog exactly as it currently works.

**Comment by brettimus** [comment]
I added some microcopy to the top of the tooltip. Lemme know if you all would like it removed and/or modified bc reasons.

![image](https://cloud.githubusercontent.com/assets/3201327/12558619/67ce2bd6-c345-11e5-95df-7ce87f23b51e.png)
