### ISSUE TITLE
Earthquakes notebook fails with checkpointing

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#23]
<img width="670" alt="screen shot 2016-01-20 at 16 00 49" src="https://cloud.githubusercontent.com/assets/177/12453361/2dcc86a4-bf93-11e5-84f8-e82bb4d24bfd.png">

**Comment by orionz** [comment]
this one was odd - not sure if it was checkpointing related...

**Comment by orionz** [comment]
nope - spoke too soon
