### ISSUE TITLE
Chart get "stuck" as a code cell result when it should be python output

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#25]
http://livebook-staging.inkandswitch.com/d/XmReJByqDo9T

<img width="598" alt="screen shot 2016-01-20 at 16 39 46" src="https://cloud.githubusercontent.com/assets/177/12453646/6ff55e2e-bf94-11e5-92ef-241bbddcb0d8.png">

**Comment by orionz** [comment]
I think this is related to the python crashing bug.
