### ISSUE TITLE
Deleting a section makes the section below have a huge font size

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#26]
Steps to reproduce:

1. Load a new welcome notebook
2. Click "Prose editor" header and select that line and the following, like so:

<img width="303" alt="screen shot 2016-01-20 at 16 41 49" src="https://cloud.githubusercontent.com/assets/177/12453727/dc9ab2e0-bf94-11e5-950b-22706d9d3815.png">

3. Press backspace
4. Now the next section header is huge:

<img width="325" alt="screen shot 2016-01-20 at 16 42 09" src="https://cloud.githubusercontent.com/assets/177/12453734/e3254cba-bf94-11e5-82a5-2b7e48ad3cae.png">

**Comment by brettimus** [comment]
Agh contenteditable is so weird. 

Reproducing reliably is tricky, but here's what I got:

**To reproduce**

* Select all text as shown in the first screen grab
* Use arrow key to extend selection beyond period in “new code cell.” 
* Hit delete

Second step there was key to reproduce for me.

**Comment by adamwiggins** [comment]
verified fix
