### ISSUE TITLE
Changing function definition should rerun dependent cells

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#27]
http://livebook-staging.inkandswitch.com/d/7anf1q5i..Nq

Steps to reproduce:

1. Define a function
2. Call that function below
<img width="497" alt="screen shot 2016-01-20 at 16 44 28" src="https://cloud.githubusercontent.com/assets/177/12453819/3bf59e1c-bf95-11e5-849c-6914b890c415.png">
3. Change the definition above, results do not update
<img width="398" alt="screen shot 2016-01-20 at 16 44 42" src="https://cloud.githubusercontent.com/assets/177/12453838/4bf3cb5e-bf95-11e5-93d1-95ef019dbfe1.png">

**Comment by orionz** [comment]
Could not reproduce - maybe you ran into the error line number mismatch bug that breaks the python executer.  Pushed a patch that hopefully fixes that.

**Comment by adamwiggins** [comment]
Confirmed fixed
