### ISSUE TITLE
Code in editor bounces up and down on each character typed

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#29]
It makes the editor feel very... excited.

http://livebook-staging.inkandswitch.com/d/hqRKhZHHrl6N

![bouncing-code](https://cloud.githubusercontent.com/assets/177/12454036/0e395634-bf96-11e5-96c5-609f88168e2b.gif)

**Comment by brettimus** [comment]
Ace is oscillating between `0px` and `-1px` top margin on the `.ace_content` div for each new char added. Possible solution is to add an `!important` directive to the line with `0px` margin-top

**Comment by luciasantamaria** [comment]
Can't reproduce. Has this been fixed in the meanwhile?

**Comment by adamwiggins** [comment]
Looks like this only happens in a new code cell, e.g. created with plus or cmd-J. Existing code cells (like the one in the linked notebook) don't have the problem.

**Comment by adamwiggins** [comment]
Verified fixed in https://github.com/inkandswitch/livebook/commit/ab7848ecf08331d6fe9b3281519ac51cda837004
