### ISSUE TITLE
Comment on last line causes strange syntax error

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#30]
Probably related to how the code is inserted into the render() or checkpoint() call\

<img width="475" alt="screen shot 2016-01-20 at 16 54 59" src="https://cloud.githubusercontent.com/assets/177/12454215/d30d05aa-bf96-11e5-9a85-3f8797c802c8.png">

**Comment by orionz** [comment]
yeaaaaahhhh...

**Comment by luciasantamaria** [comment]
Persists, see http://livebook-staging.inkandswitch.com/d/EWdOtDwCXyrI

**Comment by brettimus** [comment]
Fix confirmed
