### ISSUE TITLE
Can't create a new code cell / Uncaught IndexSizeError

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#31]
http://livebook-staging.inkandswitch.com/d/05CGBNtHrT3V

<img width="1388" alt="screen shot 2016-01-20 at 17 01 12" src="https://cloud.githubusercontent.com/assets/177/12454365/71649a42-bf97-11e5-938a-fe06a345ed8d.png">

**Comment by brettimus** [comment]
Whackabug. The specifics of this have gone away, but related #55 cropped up

**Comment by adamwiggins** [comment]
Looks like this is gone, closing
