### ISSUE TITLE
all_quakes.head() cell performance

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#32]
Was hoping the checkpointing would make this fast but it's pretty variable.

http://cl.ly/3L3b3w0Z422b

**Comment by orionz** [comment]
Hmmm... 

I benched marked it locally and it took 8ms to re-run that section with head() b/c of checkpointing.  I tried it on staging and did not experience the kind of delay you did.

Maybe: checkpointing wasnt deployed yet?
Or: It was busy grinding on a slow running block of code below and that added latency to re-running the head()?

Not sure.

**Comment by adamwiggins** [comment]
Just re-tried and it's fast now, so maybe it was not yet deployed. Closing.
