### ISSUE TITLE
Notebook title ghost text sometimes appears when a title exists

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#33]
http://livebook-staging.inkandswitch.com/d/VUAsZ6Fk3baM

<img width="628" alt="screen shot 2016-01-20 at 17 23 05" src="https://cloud.githubusercontent.com/assets/177/12455085/8888b4f8-bf9a-11e5-9c57-49e5a4102536.png">

**Comment by brettimus** [comment]
this happens when the first line is not an `H1` tag.

feature enhancement would be to guess the title from the imported doc, or tweak sample notebooks for now

**Comment by brettimus** [comment]
Waiting for input on preferred means of handling title workflow 

cc @luciasantamaria @adamwiggins

**Comment by adamwiggins** [comment]
I like the idea of treating the first line (or first 100 chars) of the notebook, regardless of its tag, as the notebook title. Is that easy to implement?

But regardless of that, we should definitely solve this for sample notebooks. Do we have any that don't have a first line in the format of "# The Title"? If so seems like an easy fix.

**Comment by brettimus** [comment]
Just earthquakes. I'll tweak that sample and work on first-line-qua-title

**Comment by luciasantamaria** [comment]
Behaviour is correct if I select the title until the last character and press delete. 
But if I double-click to select the whole line and press delete, the prose underneath gets promoted to title.

**Comment by brettimus** [comment]
Similar contenteditable / selection weirdness to #51
