### ISSUE TITLE
Can't c&p error messages

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#36]
When an error message is displayed in red I try selecting it to cmd+C/cmd+V it, but that's not possible. 
It is very annoying not to be able to c&p error messages.

**Comment by brettimus** [comment]
Are you trying to select via double-click?

**Comment by luciasantamaria** [comment]
Double-click: nothing gets selected.
Click-and-drag mouse: text gets selected but unselects when releasing the mouse.
