### ISSUE TITLE
Chrome in win: Typography

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#39]
Font doesn't look as nice as in Mac.
Text on code cells too small in comparison with prose font size.

![chromewin](https://cloud.githubusercontent.com/assets/4469749/12516331/3549beb0-c12d-11e5-841e-711b904503b0.PNG)

**Comment by adamwiggins** [comment]
Ah yes... we're using a Mac-only font for monospace, should be fixed when we redo the typefaces next week.

**Comment by adamwiggins** [comment]
Looking pretty good now:

![screenshot 4](https://cloud.githubusercontent.com/assets/177/12788326/5afeeee4-ca99-11e5-8b30-162155db1cfb.png)

Avatar name could use a bit of attention but going to call this good enough for now.
