### ISSUE TITLE
Android: various

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#47]
- Left margin too narrow
- Text in code cell too small
- Selecting text doesn't open the medium formatter, but the regular Android menu (with c&p options), which I guess is normal.

This is something for design and fit&finish next week.

![screenshot_2016-01-22-18-17-54](https://cloud.githubusercontent.com/assets/4469749/12522623/f8aa88c0-c151-11e5-88fb-7ba37bfb161b.png)

**Comment by adamwiggins** [comment]
How't this?

![2016-02-04 13 23 12](https://cloud.githubusercontent.com/assets/177/12816168/21fedf34-cb4b-11e5-8408-2b425f3beb0c.png)

![2016-02-04 13 23 20](https://cloud.githubusercontent.com/assets/177/12816170/242b8eba-cb4b-11e5-99f9-35470d367aa2.png)

**Comment by luciasantamaria** [comment]
Yes, beautiful.
