### ISSUE TITLE
Adding code cell broken in production

### ISSUE THREAD

**Issue by brettimus** [inkandswitch/livebook#48]
The contents of a new code cell inserted into the document do not get evaluated because adding a new code cell throws an error.

To reproduce:

1. Open livebook.inkandswitch.com
2. Under the first block of text beneath **Prose editor**, add a code cell.
3. Search console for `Uncaught TypeError: Cannot read property 'split' of undefined` coming from the worker.js file

**Comment by brettimus** [comment]
Awaiting fix confirmation @luciasantamaria @adamwiggins 

(No longer experiencing this bug locally or in staging)

**Comment by luciasantamaria** [comment]
Confirmed fixed.
