### ISSUE TITLE
Modifying headings does not trigger editor re-render

### ISSUE THREAD

**Issue by brettimus** [inkandswitch/livebook#54]
Occasionally, adding + removing line breaks around a heading does not trigger a rerender in the editor. This is causing two separate UI annoyances. Either:

* a strange looking ghost title (see: #33) 
* code cells overlapping prose (see: below)

![image](https://cloud.githubusercontent.com/assets/3201327/12586757/675d29ba-c406-11e5-94a9-2225b88e6a1d.png)

**Comment by brettimus** [comment]
If the text inside a heading is (miraculously) surrounded in a span, this bug seems to go away.

**Comment by brettimus** [comment]
Subsumes #33

**Comment by brettimus** [comment]
Awaiting fix confirmation from @adamwiggins @luciasantamaria

**Comment by luciasantamaria** [comment]
Nice! Confirmed fix.
