### ISSUE TITLE
Code cells pile on the top after reloading

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#58]
Steps to reproduce:
- fork quakes notebook
- wait for runtime to load
- reload page
- cells are on top and text is at the bottom

<img width="888" alt="screen shot 2016-01-29 at 18 18 20" src="https://cloud.githubusercontent.com/assets/4469749/12682618/b58e5d38-c6b4-11e5-9b1e-3258f0a0d4fb.png">

**Comment by brettimus** [comment]
Should be fixed by 671ac13 :sparkles:

**Comment by luciasantamaria** [comment]
Confirm fix.
