### ISSUE TITLE
Table results missing border

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#61]
How it looks now:

<img width="732" alt="screen shot 2016-02-01 at 20 25 58" src="https://cloud.githubusercontent.com/assets/177/12728421/1487c22e-c922-11e5-907e-f5fa33a12173.png">

How it should look:

<img width="737" alt="screen shot 2016-02-01 at 20 25 48" src="https://cloud.githubusercontent.com/assets/177/12728415/109180d8-c922-11e5-9209-5343a4716e9b.png">

**Comment by luciasantamaria** [comment]
It looks like this on Chrome Version 47.0.2526.111 (64-bit)

<img width="639" alt="screen shot 2016-02-05 at 16 20 51" src="https://cloud.githubusercontent.com/assets/4469749/12850348/8ec0aa2e-cc24-11e5-89f4-a3ce6d5b88be.png">

**Comment by adamwiggins** [comment]
Border appears on Chrome 48, but not on Chrome 47. I'm ok to not worry about the older version.

Spun out #81 and closing this one.
