### ISSUE TITLE
Numbers in table output: don't force decimal format, add commas

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#62]
* Don't display .000000 for numerics
* Use commas for 10,000 and higher

How it looks now:

<img width="350" alt="screen shot 2016-02-01 at 20 39 47" src="https://cloud.githubusercontent.com/assets/177/12728898/4d2270aa-c924-11e5-92a8-6b901c94d1ef.png">

How it should look:

<img width="346" alt="screen shot 2016-02-01 at 20 41 15" src="https://cloud.githubusercontent.com/assets/177/12728901/50912952-c924-11e5-9763-cf8b6b7a25d9.png">

**Comment by brettimus** [comment]
Addressed in 93fe5d8, awaiting review

**Comment by adamwiggins** [comment]
beautiful
