### ISSUE TITLE
Layered bar plot doesn't work

### ISSUE THREAD

**Issue by luciasantamaria** [inkandswitch/livebook#74]
It should display 3 bar plots on top of each other in 3 different colors. 

<img width="612" alt="screen shot 2016-02-02 at 22 29 40" src="https://cloud.githubusercontent.com/assets/4469749/12764955/8d2c9a30-c9fc-11e5-882c-7ed568055bc9.png">

**Comment by adamwiggins** [comment]
Status on this one?

**Comment by luciasantamaria** [comment]
Fixed.
