### ISSUE TITLE
Empty code cell at the bottom of earthquakes & monte carlo

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#80]
Kind of confusing / distracting when you get to the bottom and there's a blank code cell. Was this a mistake, or is it useful for something?

<img width="360" alt="screen shot 2016-02-04 at 17 12 06" src="https://cloud.githubusercontent.com/assets/177/12821166/89072a8a-cb62-11e5-9519-4cbad93a5857.png">

<img width="243" alt="screen shot 2016-02-04 at 17 12 19" src="https://cloud.githubusercontent.com/assets/177/12821176/8adf841a-cb62-11e5-92dc-f25f430017f3.png">

**Comment by luciasantamaria** [comment]
Fixed via https://github.com/inkandswitch/livebook/commit/33a00bb0366d24799f9745dea947ad5ee85f77a0
